TICKER = "AAPL"
MAX_POSITION_SIZE = 1000  
STRIKE_SELECTION_DELTA = 0.25
ROLL_THRESHOLD = 1.02     
KALMAN_Q = 1e-5           
KALMAN_R = 1e-3           

API_KEY = "PROD_SECURE_TOKEN_XYZ"
LOG_LEVEL = "INFO"