TICKER = "TSLA"
CONTRACT_TYPE = "PUT"

TARGET_DELTA = -0.25         
HURST_LOOKBACK = 100         
REBALANCE_FREQUENCY = "1H"   

MAX_POSITION_SIZE_SHARES = 500
SQUEEZE_THRESHOLD_Z = 2.0    
MAINTENANCE_MARGIN = 0.30    
BORROW_COST_LIMIT = 0.05     

ENV = "PRODUCTION"           
LOG_PATH = "./logs/strategy.log"